### ISSUE TITLE
Synchronization of the 4 screen videos - Biennale

### ISSUE THREAD

**Issue by LAAP** [ThomasLengeling/MultifoldDisplay#1]
@ThomasLengeling , 

Can we validate that the synchronization of the 4th videos so "skipping frame" doesn't happen, so they run in parallel and finish at the same time?

**Comment by ThomasLengeling** [comment]
Does this happen to you? can you show me when the skipping frame happens to you so that I can fix the issue

Here is the section that manages the parallel synchronization:

https://github.com/ThomasLengeling/MultifoldDisplay/blob/master/MultifoldApp/src/ofApp.cpp#L148
